//! Source-to-session acceptance checks. Golden strings were generated by the
//! independent integer reference documented in data/generator-v1-golden.json.
//! These tests do not enter raw mode; the executable/PTY gate covers that boundary.

use std::{
    fs,
    io::{self, Read},
    sync::{
        Arc,
        atomic::{AtomicUsize, Ordering},
    },
};

use clack::{
    cli::Cli,
    config::{Config, Paths},
    content::{
        self, GenerationIdentity, Generator, InputPolicy, Modifiers, PackMetadata, QuoteLength,
        Quotes, content_hash,
    },
    engine::{Action, Completion, GeneratorParameters, Mode, Policy, State},
    sample::{Samples, load_pack, read_bounded},
};
use clap::Parser;
use serde::Deserialize;
use tempfile::TempDir;

struct Fixture {
    directory: TempDir,
    paths: Paths,
}

impl Fixture {
    fn new() -> Self {
        let directory = tempfile::tempdir().unwrap();
        let data = directory.path().join("isolated-data");
        let paths = Paths {
            config: directory.path().join("config.toml"),
            database: data.join("history.sqlite3"),
            languages: data.join("languages"),
            data,
        };
        Self { directory, paths }
    }

    fn import(&self, id: &str, words: &str) -> PackMetadata {
        let metadata = PackMetadata {
            schema_version: 1,
            id: id.into(),
            language_tag: "en".into(),
            revision: "fixture-1".into(),
            source: "Original acceptance fixture".into(),
            license: "CC0-1.0".into(),
            content_hash: content_hash(words.as_bytes()),
            text_direction: "ltr".into(),
            supported_input_policy: InputPolicy::Prose,
            token_count: words.lines().count(),
        };
        let path = self.paths.languages.join(id);
        fs::create_dir_all(&path).unwrap();
        fs::write(path.join("words.txt"), words).unwrap();
        fs::write(
            path.join("metadata.json"),
            serde_json::to_vec(&metadata).unwrap(),
        )
        .unwrap();
        metadata
    }
}

fn configured(args: &[&str], mut config: Config) -> (Cli, Config) {
    let cli = Cli::try_parse_from(std::iter::once("clack").chain(args.iter().copied())).unwrap();
    cli.apply(&mut config).unwrap();
    (cli, config)
}

fn modifiers(parameters: GeneratorParameters, punctuation: bool, numbers: bool) -> Modifiers {
    Modifiers {
        punctuation,
        numbers,
        sentence_min_words: parameters.sentence_min_words,
        sentence_max_words: parameters.sentence_max_words,
        comma_percent: parameters.comma_percent,
        number_percent: parameters.number_percent,
        number_min_digits: parameters.number_min_digits,
        number_max_digits: parameters.number_max_digits,
    }
}

#[derive(Deserialize)]
struct GoldenFile {
    generator_version: u32,
    cases: Vec<Golden>,
}

#[derive(Deserialize)]
struct Golden {
    seed: u64,
    pack_id: String,
    pack_revision: String,
    pack_content_hash: String,
    punctuation: bool,
    numbers: bool,
    word_count: u32,
    text: String,
}

#[test]
fn cli_pack_seed_and_effective_defaults_match_independent_golden_replays() {
    let fixture = Fixture::new();
    let goldens: GoldenFile =
        serde_json::from_str(include_str!("../data/generator-v1-golden.json")).unwrap();
    for golden in goldens.cases {
        let seed = golden.seed.to_string();
        let count = golden.word_count.to_string();
        let punctuation = format!("--punctuation={}", golden.punctuation);
        let numbers = format!("--numbers={}", golden.numbers);
        let (cli, config) = configured(
            &[
                "--words",
                &count,
                "--seed",
                &seed,
                "--language",
                &golden.pack_id,
                &punctuation,
                &numbers,
            ],
            Config::default(),
        );
        let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
        let sample = sources.next(&config).unwrap();
        assert_eq!(sample.text, golden.text, "{} seed {seed}", golden.pack_id);
        let spec = sample.engine.spec();
        assert_eq!(spec.seed, golden.seed);
        assert_eq!(spec.source_id, golden.pack_id);
        assert_eq!(spec.source_revision, golden.pack_revision);
        assert_eq!(spec.content_hash, golden.pack_content_hash);
        assert_eq!(spec.generator_version, goldens.generator_version);
        assert_eq!(spec.generator_parameters, GeneratorParameters::default());
        assert!(spec.approved_content && spec.explicit_seed);
        assert!(sample.generator.is_none());
        assert!(!sample.engine.snapshot().personal_best_eligible);
    }
}

#[test]
fn preset_parameters_survive_cli_overrides_and_are_effective_in_generated_text() {
    let fixture = Fixture::new();
    fs::write(
        &fixture.paths.config,
        r#"schema_version = 1
[test]
mode = "time"
seconds = 30
punctuation = false
numbers = false
[presets.synthetic.test]
mode = "words"
words = 17
punctuation = true
numbers = true
[presets.synthetic.test.generator_parameters]
sentence_min_words = 2
sentence_max_words = 2
comma_percent = 100
number_percent = 100
number_min_digits = 3
number_max_digits = 3
"#,
    )
    .unwrap();
    let original = fs::read(&fixture.paths.config).unwrap();
    let base = Config::read(&fixture.paths.config).unwrap();
    let (cli, config) = configured(
        &["--preset", "synthetic", "--words", "7", "--seed", "42"],
        base,
    );
    let expected = GeneratorParameters {
        sentence_min_words: 2,
        sentence_max_words: 2,
        comma_percent: 100,
        number_percent: 100,
        number_min_digits: 3,
        number_max_digits: 3,
    };
    assert_eq!(config.test.generator_parameters, expected);
    let sample = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    let spec = sample.engine.spec();
    assert_eq!(spec.generator_parameters, expected);
    assert!(spec.punctuation && spec.numbers);
    let words: Vec<_> = sample.text.split(' ').collect();
    assert_eq!(words.len(), 7);
    for (index, word) in words.iter().enumerate() {
        assert_eq!(word.len(), 4, "every generated number has three digits");
        assert!(word[..3].bytes().all(|byte| byte.is_ascii_digit()));
        assert_ne!(word.as_bytes()[0], b'0');
        let punctuation = if index % 2 == 1 || index == 6 {
            '.'
        } else {
            ','
        };
        assert!(word.ends_with(punctuation));
    }
    let identity = GenerationIdentity {
        generator_version: spec.generator_version,
        prng: "splitmix64".into(),
        seed: spec.seed,
        pack_id: spec.source_id.clone(),
        pack_revision: spec.source_revision.clone(),
        pack_content_hash: spec.content_hash.clone(),
        modifiers: modifiers(spec.generator_parameters, spec.punctuation, spec.numbers),
    };
    let identity: GenerationIdentity =
        serde_json::from_slice(&serde_json::to_vec(&identity).unwrap()).unwrap();
    let replay = Generator::from_identity(content::bundled_pack("english_200").unwrap(), &identity)
        .unwrap()
        .finite_words(7)
        .unwrap();
    assert_eq!(replay.text, sample.text);
    assert_eq!(fs::read(&fixture.paths.config).unwrap(), original);
}

#[test]
fn word_count_boundaries_are_exact_and_punctuation_closes_the_final_sentence() {
    let fixture = Fixture::new();
    for count in [1_u32, 4, 10, 25, 50, 100, 10_000] {
        for punctuation in [false, true] {
            let count = count.to_string();
            let flag = format!("--punctuation={punctuation}");
            let (cli, config) = configured(
                &["--words", &count, "--seed", "42", &flag],
                Config::default(),
            );
            let sample = Samples::prepare(&cli, &config, &fixture.paths)
                .unwrap()
                .next(&config)
                .unwrap();
            assert_eq!(
                sample.text.split_whitespace().count(),
                config.test.words as usize
            );
            assert_eq!(sample.engine.tokens().len(), config.test.words as usize);
            assert!(!sample.text.ends_with(' '));
            assert_eq!(sample.text.ends_with('.'), punctuation);
        }
    }
}

#[test]
fn seeded_new_samples_form_a_replayable_sequence_without_repeating_the_first_sample() {
    let fixture = Fixture::new();
    let (cli, config) = configured(
        &[
            "--words",
            "25",
            "--seed",
            "42",
            "--punctuation",
            "--numbers",
        ],
        Config::default(),
    );
    let mut first = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let mut second = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let mut previous = String::new();
    for index in 0..10 {
        let a = first.next(&config).unwrap();
        let b = second.next(&config).unwrap();
        assert_eq!(a.text, b.text);
        assert_eq!(a.engine.spec(), b.engine.spec());
        assert!(a.engine.spec().explicit_seed);
        assert_ne!(a.text, previous);
        if index == 0 {
            assert_eq!(a.engine.spec().seed, 42);
        }
        previous = a.text;
    }
}

#[test]
fn timed_repeat_preserves_prepared_text_and_the_future_generator_state_once() {
    let fixture = Fixture::new();
    let (cli, config) = configured(
        &["--time", "30", "--seed", "42", "--punctuation", "--numbers"],
        Config::default(),
    );
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let mut original = sources.next(&config).unwrap();
    original.lookahead(10_000).unwrap();
    let typed: String = original.text.chars().take(1000).collect();
    for (index, character) in typed.char_indices().enumerate() {
        original.engine.apply(
            Action::Text(&character.1.to_string()),
            1_000_000 + index as u64,
        );
    }
    assert_eq!(original.engine.state(), State::Running);
    assert!(original.engine.counts().attempts_total > 0);

    let mut repeated = sources.repeat(&original).unwrap();
    assert_eq!(repeated.text, original.text);
    assert_eq!(repeated.engine.state(), State::Ready);
    assert_eq!(repeated.engine.counts().attempts_total, 0);
    assert_eq!(repeated.engine.started_at(), None);
    assert!(repeated.engine.spec().repeated);
    assert!(repeated.engine.spec().practice_reason.is_some());
    let mut expected_spec = original.engine.spec().clone();
    expected_spec.repeated = repeated.engine.spec().repeated;
    expected_spec.practice_reason = repeated.engine.spec().practice_reason.clone();
    assert_eq!(repeated.engine.spec(), &expected_spec);
    assert_eq!(
        original.generator.as_ref().unwrap().generated_words(),
        repeated.generator.as_ref().unwrap().generated_words()
    );

    let desired_end = original.engine.prepared_target_units() + 6000;
    original
        .lookahead(desired_end - original.engine.logical_target_position())
        .unwrap();
    repeated.lookahead(desired_end).unwrap();
    assert_eq!(repeated.text, original.text);
    let mut future_a = original.generator.as_ref().unwrap().clone();
    let mut future_b = repeated.generator.as_ref().unwrap().clone();
    for _ in 0..8 {
        assert_eq!(
            future_a.next_chunk().unwrap(),
            future_b.next_chunk().unwrap()
        );
    }
    let mut from_seed = Generator::new(
        content::bundled_pack("english_200").unwrap(),
        42,
        modifiers(config.test.generator_parameters, true, true),
    )
    .unwrap();
    let prepared_words = repeated.text.split_whitespace().count();
    assert_eq!(
        from_seed.next_words(prepared_words).unwrap().text,
        repeated.text
    );
}

#[test]
fn timed_lookahead_is_independent_of_requested_chunk_sizes() {
    let fixture = Fixture::new();
    let (cli, config) = configured(
        &[
            "--time",
            "30",
            "--seed",
            "18446744073709551615",
            "--language",
            "french_200",
        ],
        Config::default(),
    );
    let mut a = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    let mut b = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    for units in [2000, 3500, 5000, 8000] {
        a.lookahead(units).unwrap();
    }
    b.lookahead(8000).unwrap();
    assert_eq!(a.text, b.text);
    assert_eq!(
        a.engine.prepared_target_units(),
        b.engine.prepared_target_units()
    );
    assert_eq!(
        a.generator.as_ref().unwrap().generated_words(),
        b.generator.as_ref().unwrap().generated_words()
    );
}

#[test]
fn quote_categories_never_immediately_repeat_and_keep_catalog_identity() {
    let fixture = Fixture::new();
    let quotes = Quotes::bundled().unwrap();
    for (name, length) in [
        ("short", QuoteLength::Short),
        ("medium", QuoteLength::Medium),
        ("long", QuoteLength::Long),
        ("extended", QuoteLength::Extended),
    ] {
        let (cli, config) = configured(
            &[
                "--quote",
                "--length",
                name,
                "--seed",
                "42",
                "--punctuation",
                "--numbers",
            ],
            Config::default(),
        );
        let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
        let mut previous = String::new();
        for _ in 0..12 {
            let sample = sources.next(&config).unwrap();
            let spec = sample.engine.spec();
            let quote = quotes.get(&spec.source_id).unwrap();
            assert!(length.contains(sample.text.split_whitespace().count()));
            assert_ne!(spec.source_id, previous);
            assert_eq!(
                sample.text, quote.text,
                "quote content is not transformed by random modifiers"
            );
            assert_eq!(spec.source_revision, quote.revision);
            assert_eq!(spec.content_hash, quote.content_hash);
            assert!(spec.approved_content);
            assert!(sample.generator.is_none());
            previous.clone_from(&spec.source_id);
        }
    }
}

#[test]
fn explicit_quote_id_is_stable_and_unknown_id_diagnostics_are_neutral() {
    let fixture = Fixture::new();
    let quote = &Quotes::bundled().unwrap().passages[0];
    let (cli, config) = configured(&["--quote-id", &quote.id], Config::default());
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    for _ in 0..3 {
        let sample = sources.next(&config).unwrap();
        assert_eq!(sample.text, quote.text);
        assert_eq!(sample.engine.spec().source_id, quote.id);
    }
    let secret = "private-unknown-quote-label";
    let (cli, config) = configured(&["--quote-id", secret], Config::default());
    let error = Samples::prepare(&cli, &config, &fixture.paths)
        .and_then(|mut sources| sources.next(&config))
        .err()
        .expect("unknown ID must fail before a Ready sample is returned");
    assert!(!error.contains(secret));
}

#[test]
fn private_custom_file_and_literal_share_neutral_identity_and_normalized_hash() {
    let fixture = Fixture::new();
    let path = fixture
        .directory
        .path()
        .join("private-account-statement.txt");
    let secret = "  confidential_cafe\u{301}\r\n\tprivate_balance  ";
    fs::write(&path, secret).unwrap();
    let expected = "confidential_café private_balance";
    let mut base = Config::default();
    base.privacy.store_custom_text = true;
    base.privacy.store_event_trace = true;
    let (file_cli, file_config) = configured(
        &[
            "--file",
            path.to_str().unwrap(),
            "--private",
            "--punctuation",
            "--numbers",
        ],
        base,
    );
    assert!(!file_config.privacy.save_results);
    assert!(!file_config.privacy.store_custom_text);
    assert!(!file_config.privacy.store_event_trace);
    let mut sources = Samples::prepare(&file_cli, &file_config, &fixture.paths).unwrap();
    let sample = sources.next(&file_config).unwrap();
    assert_eq!(sample.text, expected);
    assert_eq!(sample.engine.spec().source_id, "custom");
    assert_eq!(
        sample.engine.spec().content_hash,
        content_hash(expected.as_bytes())
    );
    assert!(!sample.engine.spec().approved_content);
    let serialized = serde_json::to_string(sample.engine.spec()).unwrap();
    assert!(!serialized.contains(path.to_str().unwrap()));
    assert!(!serialized.contains("private-account-statement"));
    assert!(!serialized.contains("confidential_caf"));
    assert!(!serialized.contains("private_balance"));
    assert_eq!(sources.repeat(&sample).unwrap().text, expected);

    let (literal_cli, literal_config) = configured(&["--text", expected], Config::default());
    let literal = Samples::prepare(&literal_cli, &literal_config, &fixture.paths)
        .unwrap()
        .next(&literal_config)
        .unwrap();
    assert_eq!(literal.text, sample.text);
    assert_eq!(
        literal.engine.spec().content_hash,
        sample.engine.spec().content_hash
    );
    assert!(
        !fixture.paths.data.exists(),
        "source preparation has no persistence side effect"
    );
}

#[test]
fn exact_custom_preserves_literal_units_and_opt_in_nfc_changes_identity() {
    let fixture = Fixture::new();
    let original = "\tlet cafe\u{301} = 1;\r\n    cafe\u{301}\n";
    let expected = "\tlet cafe\u{301} = 1;\n    cafe\u{301}\n";
    let (cli, config) = configured(&["--text", original, "--exact"], Config::default());
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let sample = sources.next(&config).unwrap();
    assert_eq!(sample.text, expected);
    assert_eq!(sample.engine.spec().policy, Policy::Exact);
    assert_eq!(sample.engine.spec().completion, Completion::Confirm);
    assert!(!sample.engine.spec().normalize);
    assert_eq!(
        sample.engine.spec().content_hash,
        content_hash(expected.as_bytes())
    );
    assert_eq!(sources.repeat(&sample).unwrap().text, expected);

    let (cli, config) = configured(
        &["--text", original, "--exact", "--normalize-exact"],
        Config::default(),
    );
    let normalized = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    assert_eq!(normalized.text, "\tlet café = 1;\n    café\n");
    assert!(normalized.engine.spec().normalize);
    assert_ne!(
        normalized.engine.spec().content_hash,
        sample.engine.spec().content_hash
    );
}

#[test]
fn code_preset_uses_exact_custom_file_when_supplied_and_bundled_source_otherwise() {
    let fixture = Fixture::new();
    let path = fixture.directory.path().join("private-code.rs");
    let source = "fn main() {\r\n\tlet x = 1;\r\n}\r\n";
    fs::write(&path, source).unwrap();
    let (cli, config) = configured(
        &["--preset", "code", "--file", path.to_str().unwrap()],
        Config::default(),
    );
    assert_eq!(config.test.mode, Mode::Code);
    assert_eq!(config.test.policy, Policy::Exact);
    let sample = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    assert_eq!(sample.text, source.replace("\r\n", "\n"));
    assert_eq!(sample.engine.spec().source_id, "code");
    assert!(!sample.engine.spec().approved_content);
    let (cli, config) = configured(&["--code"], Config::default());
    let bundled = Samples::prepare(&cli, &config, &fixture.paths)
        .unwrap()
        .next(&config)
        .unwrap();
    assert_eq!(bundled.text, content::code_preset().unwrap().text);
    assert!(bundled.engine.spec().approved_content);
}

#[test]
fn invalid_custom_content_is_rejected_before_a_session_and_never_echoed() {
    let fixture = Fixture::new();
    let path = fixture.directory.path().join("private-account-source.txt");
    let (cli, config) = configured(
        &["--file", path.to_str().unwrap(), "--private"],
        Config::default(),
    );
    let pathological = format!("private_sentinel_a{}", "\u{301}".repeat(33)).into_bytes();
    let invalid = [
        b"private_sentinel_\xff".to_vec(),
        b"private_sentinel_\x1b[31m".to_vec(),
        "private_sentinel_\u{202e}text".as_bytes().to_vec(),
        b" \t\r\n  ".to_vec(),
        pathological,
    ];
    for bytes in invalid {
        fs::write(&path, bytes).unwrap();
        let error = Samples::prepare(&cli, &config, &fixture.paths)
            .err()
            .expect("invalid source rejected");
        assert!(!error.contains("private_sentinel"));
        assert!(!error.contains(path.to_str().unwrap()));
        assert!(!error.contains('\u{1b}'));
        assert!(!error.contains('\u{202e}'));
        assert!(!fixture.paths.data.exists());
    }
    fs::remove_file(&path).unwrap();
    let error = Samples::prepare(&cli, &config, &fixture.paths)
        .err()
        .expect("missing source rejected");
    assert!(!error.contains(path.to_str().unwrap()));
}

struct Endless {
    received: Arc<AtomicUsize>,
}

impl Read for Endless {
    fn read(&mut self, buffer: &mut [u8]) -> io::Result<usize> {
        buffer.fill(b'a');
        self.received.fetch_add(buffer.len(), Ordering::Relaxed);
        Ok(buffer.len())
    }
}

#[test]
fn bounded_reader_accepts_the_limit_and_reads_only_one_extra_byte_to_reject() {
    let limit = content::MAX_CUSTOM_BYTES;
    let bytes = vec![b'a'; limit];
    assert_eq!(read_bounded(bytes.as_slice(), limit).unwrap(), bytes);
    let received = Arc::new(AtomicUsize::new(0));
    let error = read_bounded(
        Endless {
            received: Arc::clone(&received),
        },
        limit,
    )
    .unwrap_err();
    assert_eq!(error.kind(), io::ErrorKind::InvalidData);
    assert_eq!(received.load(Ordering::Relaxed), limit + 1);
    assert!(read_bounded(&b""[..], 0).unwrap().is_empty());
    assert_eq!(
        read_bounded(&b"x"[..], 0).unwrap_err().kind(),
        io::ErrorKind::InvalidData
    );
}

#[test]
fn bounded_reader_does_not_overflow_for_the_largest_usize_limit() {
    assert_eq!(read_bounded(&b"ok"[..], usize::MAX).unwrap(), b"ok");
}

#[test]
fn oversized_file_and_literal_sources_are_rejected_before_preparing_a_session() {
    let fixture = Fixture::new();
    let path = fixture.directory.path().join("large-private-source.txt");
    fs::File::create(&path)
        .unwrap()
        .set_len((content::MAX_CUSTOM_BYTES + 1) as u64)
        .unwrap();
    let (cli, config) = configured(&["--file", path.to_str().unwrap()], Config::default());
    let error = Samples::prepare(&cli, &config, &fixture.paths)
        .err()
        .expect("source exceeds cap");
    assert!(error.contains("1048576"));
    assert!(!error.contains(path.to_str().unwrap()));
    let literal = "a".repeat(content::MAX_CUSTOM_BYTES + 1);
    let (cli, config) = configured(&["--text", &literal], Config::default());
    assert!(Samples::prepare(&cli, &config, &fixture.paths).is_err());
}

#[test]
fn missed_practice_expands_a_legal_large_custom_token_to_all_25_original_words() {
    let fixture = Fixture::new();
    let source = "a".repeat(content::MAX_CUSTOM_BYTES / content::PRACTICE_WORDS + 1);
    let (cli, config) = configured(&["--text", &source], Config::default());
    let mut samples = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let mut original = samples.next(&config).unwrap();
    original.engine.apply(Action::Text("x"), 0);
    original.engine.apply(Action::Text(" "), 1);
    assert_eq!(original.engine.state(), State::Results);
    let mut practice_config = config.clone();
    practice_config.test.mode = Mode::Words;
    practice_config.test.words = content::PRACTICE_WORDS as u32;
    let practice = samples
        .practice(&practice_config, &original, content::PracticeKind::Missed)
        .unwrap();
    assert!(practice.text.len() > content::MAX_CUSTOM_BYTES);
    assert!(practice.text.len() <= content::MAX_PRACTICE_BYTES);
    assert_eq!(practice.engine.tokens().len(), content::PRACTICE_WORDS);
    assert!(practice.text.split(' ').all(|word| word == source));
    assert_eq!(
        practice.engine.spec().practice_reason.as_deref(),
        Some("missed-word practice")
    );
    assert!(!practice.engine.snapshot().personal_best_eligible);
    assert_eq!(original.engine.missed_words(), [source]);
}

#[test]
fn imported_pack_is_prepared_once_owned_by_samples_and_released_by_generator() {
    let fixture = Fixture::new();
    let metadata = fixture.import("local_fixture", "alpha\nbeta\ngamma\n");
    let (cli, config) = configured(
        &[
            "--time",
            "30",
            "--seed",
            "42",
            "--language",
            "local_fixture",
        ],
        Config::default(),
    );
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    let owner = load_pack("local_fixture", &fixture.paths).unwrap();
    let weak = Arc::downgrade(&owner);
    let mut generator =
        Generator::from_shared(Arc::clone(&owner), 42, Modifiers::default()).unwrap();
    assert_eq!(Arc::strong_count(&owner), 2);
    drop(owner);
    fs::remove_dir_all(&fixture.paths.languages).unwrap();
    assert!(weak.upgrade().is_some());
    assert_eq!(generator.next_words(1).unwrap().text, "beta");
    drop(generator);
    assert!(
        weak.upgrade().is_none(),
        "owned generator must not leak an imported pack"
    );

    let mut sample = sources.next(&config).unwrap();
    assert_eq!(sample.engine.spec().source_id, metadata.id);
    assert_eq!(sample.engine.spec().source_revision, metadata.revision);
    assert_eq!(sample.engine.spec().content_hash, metadata.content_hash);
    assert!(!sample.engine.spec().approved_content);
    sample.lookahead(10_000).unwrap();
    let repeated = sources.repeat(&sample).unwrap();
    assert_eq!(sample.text, repeated.text);
    assert!(
        sample
            .text
            .split_whitespace()
            .all(|word| ["alpha", "beta", "gamma"].contains(&word))
    );
    assert!(
        sources.next(&config).is_ok(),
        "prepared source does not reopen removed files"
    );
}

#[test]
fn imported_pack_loading_rejects_traversal_mismatched_identity_and_oversized_files() {
    let fixture = Fixture::new();
    for id in [
        "",
        "..",
        "../private",
        "/private",
        "bad/name",
        "bad\\name",
        ".hidden",
        "two..dots",
    ] {
        assert!(load_pack(id, &fixture.paths).is_err());
    }
    fixture.import("original", "alpha\nbeta\n");
    fs::rename(
        fixture.paths.languages.join("original"),
        fixture.paths.languages.join("other"),
    )
    .unwrap();
    assert!(load_pack("other", &fixture.paths).is_err());
    fixture.import("oversize", "alpha\nbeta\n");
    let directory = fixture.paths.languages.join("oversize");
    fs::File::create(directory.join("metadata.json"))
        .unwrap()
        .set_len(64 * 1024 + 1)
        .unwrap();
    assert!(load_pack("oversize", &fixture.paths).is_err());
    fs::File::create(directory.join("words.txt"))
        .unwrap()
        .set_len((content::MAX_PACK_BYTES + 1) as u64)
        .unwrap();
    assert!(load_pack("oversize", &fixture.paths).is_err());
}

#[test]
fn changing_custom_file_reconfigures_the_prepared_source_and_hash() {
    let fixture = Fixture::new();
    let first_path = fixture.directory.path().join("first.txt");
    let second_path = fixture.directory.path().join("second.txt");
    fs::write(&first_path, "first source").unwrap();
    fs::write(&second_path, "second source").unwrap();
    let mut base = Config::default();
    base.test.mode = Mode::Custom;
    base.test.file = Some(first_path);
    let (cli, mut config) = configured(&[], base);
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    assert_eq!(sources.next(&config).unwrap().text, "first source");
    config.test.file = Some(second_path);
    sources.reconfigure(&config, &fixture.paths).unwrap();
    let next = sources.next(&config).unwrap();
    assert_eq!(next.text, "second source");
    assert_eq!(
        next.engine.spec().content_hash,
        content_hash(b"second source")
    );
}

#[test]
fn changing_custom_policy_reprepares_the_original_bytes() {
    let fixture = Fixture::new();
    let path = fixture.directory.path().join("source.txt");
    fs::write(&path, "\tfirst\r\n  second\n").unwrap();
    let mut base = Config::default();
    base.test.mode = Mode::Custom;
    base.test.file = Some(path);
    let (cli, mut config) = configured(&[], base);
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    assert_eq!(sources.next(&config).unwrap().text, "first second");
    config.test.policy = Policy::Exact;
    sources.reconfigure(&config, &fixture.paths).unwrap();
    let next = sources.next(&config).unwrap();
    assert_eq!(next.text, "\tfirst\n  second\n");
    assert_eq!(next.engine.spec().policy, Policy::Exact);

    let (cli, mut config) = configured(&["--text", "\tfirst\r\n  second\n"], Config::default());
    let mut sources = Samples::prepare(&cli, &config, &fixture.paths).unwrap();
    assert_eq!(sources.next(&config).unwrap().text, "first second");
    config.test.policy = Policy::Exact;
    sources.reconfigure(&config, &fixture.paths).unwrap();
    assert_eq!(sources.next(&config).unwrap().text, "\tfirst\n  second\n");
}

#[test]
fn cli_rejects_incompatible_sources_bounds_and_policies_before_source_preparation() {
    for arguments in [
        vec!["--time", "30", "--words", "25"],
        vec!["--text", "private", "--stdin"],
        vec!["--file", "private.txt", "--quote"],
        vec!["--time", "0"],
        vec!["--time", "3601"],
        vec!["--words", "0"],
        vec!["--words", "10001"],
        vec!["--quote", "--length", "enormous"],
    ] {
        let error = Cli::try_parse_from(std::iter::once("clack").chain(arguments.iter().copied()))
            .unwrap_err();
        assert_eq!(error.exit_code(), 2);
    }
    for arguments in [
        vec!["--time", "30", "--exact"],
        vec!["--words", "25", "--exact"],
        vec!["--quote", "--exact"],
        vec!["--time", "30", "--length", "short"],
        vec!["--text", "private", "--normalize-exact"],
        vec!["--json"],
    ] {
        let cli =
            Cli::try_parse_from(std::iter::once("clack").chain(arguments.iter().copied())).unwrap();
        assert!(cli.apply(&mut Config::default()).is_err());
    }
}
