#!/usr/bin/env python3
"""Rebuild pinned Unicode 17 uppercase mappings from verified official inputs.

Offline developer utility; never executed by import, launch, or compilation.
Acquire the files listed in unicode-case-manifest.json into --source-dir first.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def generate(source_dir):
    manifest = json.loads((ROOT / "unicode-case-manifest.json").read_text())
    sources = {}
    for source in manifest["sources"]:
        raw = (source_dir / source["filename"]).read_bytes()
        if hashlib.sha256(raw).hexdigest() != source["sha256"]:
            raise ValueError("Unicode source hash mismatch: " + source["filename"])
        sources[source["filename"]] = raw.decode("utf-8")
    mappings = {}
    for line in sources["UnicodeData.txt"].splitlines():
        fields = line.split(";")
        if fields[12]:
            mappings[int(fields[0], 16)] = [int(fields[12], 16)]
    for line in sources["SpecialCasing.txt"].splitlines():
        fields = [field.strip() for field in line.split("#", 1)[0].split(";")]
        if len(fields) >= 5 and fields[0] and not fields[4]:
            mappings[int(fields[0], 16)] = [int(value, 16) for value in fields[3].split()]
    mappings = {key: value for key, value in mappings.items() if value != [key]}
    lines = [
        "// Generated by data/rebuild_unicode_case.py from Unicode 17.0.0.",
        "// Unicode-3.0; full notice in data/licenses/Unicode-3.0.txt.",
        "// Source URLs/hashes and generation semantics: data/unicode-case-manifest.json.",
        "#[rustfmt::skip]",
        "pub(super) const UPPERCASE: &[(char, &str)] = &[",
    ]
    for codepoint, mapping in sorted(mappings.items()):
        escaped = "".join("\\u{" + format(value, "x") + "}" for value in mapping)
        lines.append("    ('\\u{" + format(codepoint, "x") + "}', \"" + escaped + "\"),")
    lines.extend([
        "];",
        "",
    ])
    return "\n".join(lines).encode(), len(mappings)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated, count = generate(arguments.source_dir)
    target = ROOT.parent / "src/content/case_tables.rs"
    if arguments.check:
        if target.read_bytes() != generated:
            raise SystemExit("pinned Unicode case table differs from verified source generation")
    else:
        target.write_bytes(generated)
    print(json.dumps({"unicode_version": "17.0.0", "mappings": count,
                      "bytes": len(generated), "sha256": hashlib.sha256(generated).hexdigest(),
                      "check": arguments.check}))
